server:
  port: 8092

spring:
  kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: orderConfirmation:dev.arena.order.producer.OrderConfirmation
  datasource:
    username: mdarena
    password:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order-service
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:9999/api/v1/customers
    product-url: http://localhost:9999/api/v1/products
    payment-url: http://localhost:9999/api/v1/payments


management:
  tracing:
    sampling:
      probability: 1.0