server:
  port: 8091

spring:
  datasource:
    username: mdarena
    password:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-service
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0